package auth

const (
	TM_CREATE_TASK           string = "TM.CREATE_TASK"
	TM_ASSIGN_TASK           string = "TM.ASSIGN_TASK"
	TM_VIEW_SELF_TASKS       string = "TM.VIEW_SELF_TASKS"
	TM_VIEW_ALL_TASKS        string = "TN.VIEW_ALL_TASKS"
	ACC_VIEW_BALANCE         string = "ACC.VIEW_BALANCE"
	ACC_VIEW_SELF_BALANCE    string = "ACC.VIEW_SELF_BALANCE"
	STAT_VIEW_PRICING_INFO   string = "STAT.VIEW_PRICING_INFO"
	STAT_VIEW_BALANCE_BY_DAY string = "STAT.VIEW_BALANCE_BY_DAY"
)
